<?php     
error_reporting(E_ERROR | E_WARNING | E_PARSE);
?>
<!DOCTYPE html>
<html>
<head>



	
	<meta http-equiv="Content-Type" content="text/html; utf-8" />

	<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400+800' rel='stylesheet' type='text/css'>
	<title>nForms - Documentation</title>


	<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/css/bootstrap-combined.min.css" rel="stylesheet">

    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/bootstrap.progress.css" rel="stylesheet">
    <link href="css/nform_style.css" rel="stylesheet">
    <link href="css/boxes.css" rel="stylesheet">
    <link href="datepicker/css/datepicker.css" rel="stylesheet">
    <link href="datepicker/css/datepicker.css" rel="stylesheet">
    <link href="http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="css/demo.css">

	<style>

	.nform
	{
		font-family: Arial;
	}

	</style>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js">
    </script>
    <script>
    jQuery.noConflict();
    </script>

    <script src='datepicker/js/bootstrap-datepicker.js'></script>
    <script src='bootstrap/js/bootstrap.min.js'></script>
    <script src='js/form.js'></script>
    <script src='ui/js/jquery-ui-1.10.0.custom.min.js'></script>
    <script src='file-upload/js/jquery.fileupload.js'></script>
    <script src='file-upload/js/jquery.iframe-transport.js'></script>
    <script src='file-upload/js/vendor/jquery.ui.widget.js'></script>
    <script src='file-upload/js/jquery.iframe-transport.js'></script>
    <script src='slider/js/jquery.anchor.js'></script>



</head>


<body data-spy='scroll' data-target="#navcover">

	<div id='navcover'>
		<ul class='nav sidebar'>
			<li><a class='anchorLink' href='#home'>Home</a></li>
			<li><a class='anchorLink' href='#contact_us'>Contact Us</a></li>
			<li><a class='anchorLink' href='#embed'>Embed Stuff</a></li>
			<li><a class='anchorLink' href='#job'>More Examples</a></li>
			<li><a></a></li>
		</ul>
	</div>

	<div style='display:none'>
		<img src='images/right2.png'>
		<img src='images/down2.png'>
	</div>

	<div class='cover_1'>

		<h1 id='home'>nForms</h1>
		<p class='author'>by nCrafts</p>
		<div>
			<a class='big-button anchorLink' id='button1' href='#contact_us'>Sample Forms</a>
			<a class='big-button' id='button2' href='login.php?email=demo&password=demo' target='_blank'>Form Builder</a>
		</div>

		<br><br><br><br>


		<h2 class='h2' id='contact_us'>Contact Us Examples</h2>
		<div class='nform_demo_cover left'>
			<h3>Simple</h3>
			<form class="nform bootstrap jean one  " action="javascript:submit_nform(679469735);" ng-style="{width: con[0].fw, borderRadius: con[0].fr, MozBorderRadius: con[0].fr, WebkitBorderRadius: con[0].fr, fontFamily: con[0].formfamily}" id="679469735">
				<input type="hidden" class="form_id" val="26">

				<div id="fe_title" class="nform_li form_title jean" ng-style="{fontSize: con[0].ft_px, borderTopLeftRadius: con[0].fr, MozBorderTopLeftRadius: con[0].fr, WebkitBorderTopLeftRadius: con[0].fr, borderTopRightRadius: con[0].fr, MozBorderTopRightRadius: con[0].fr, WebkitBorderTopRightRadius: con[0].fr, color: con[0].ft_co, backgroundColor: con[0].ft_bg, fontFamily: con[0].tfamily, fontWeight: con[0].tbold}" style="font-size: 32px;">Contact Us</div>


				<ul class="form_ul jean" style="">
					<!-- ngRepeat: el in build --><li ng-repeat="el in build" style="padding-bottom: ; padding-top: " id="fe_0" class="nform_li ng-scope nform_li_before">
					<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc}" style="font-size: 14px;">Name<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">full name here</span></span><span class="input_cover text_cover ng-scope"><input type="text" ng-style="{width: el.wid}" name="Name_text__1_0_60_field0" style="width: 220px;"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field0 valid_show"></span></span></div>
				</li><li ng-repeat="el in build" style="padding-bottom: ; padding-top: " id="fe_1" class="nform_li ng-scope">
				<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px;">Comments<span class="show_0">*</span></span><span class="cap2 " ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">further details</span></span><span class="input_cover text_cover ng-scope"><textarea rows="3" ng-style="{ width: el.wid }" name="Comments_para__0_0_60_field1" style="width: 220px;"></textarea><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field1 valid_show"></span></span></div>
			</li><li ng-repeat="el in build" style="padding-bottom: ; padding-top: " id="fe_2" class="nform_li ng-scope">
			<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px;">Captcha</span><span class="cap2 " ng-bind="el.ctcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">type the characters</span></span><span class="input_cover text_cover ng-scope"><img ng-src="php/image.php?type=one_font" title="Click to refresh" class="c_image" src="php/image.php?type=one_font"><input type="text" style="width: 90px; margin-left: 15px" name="Captcha_captcha_captcha_1___field2"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field2 valid_show"></span></span></div>
		</li>
	</ul>
	<div id="fe_submit" class="nform_li form_submit" style="position: relative; display: block"><button type="submit" class="submit_button nform_btn custom" ng-style="{background: con[0].sco, fontSize: con[0].sfs,  marginLeft: con[0].lp,  marginTop: con[0].tp,  marginBottom: con[0].bp,  marginRight: con[0].rp,  paddingTop: con[0].spad1,  paddingBottom: con[0].spad1,  paddingRight: con[0].spad2,  paddingLeft: con[0].spad2,  borderRadius: con[0].curve,  MozBorderRadius: con[0].curve,  WebkitBorderRadius: con[0].curve, fontFamily: con[0].sfamily, fontWeight: con[0].sbold, color: con[0].sbfco}" data-loading-text="Sending ..." style="background-color: rgb(245, 245, 245); font-size: 18px; margin-top: 20px; margin-bottom: 20px; padding: 12px 50px; font-family: 'Trebuchet MS'; font-weight: bold; background-position: initial initial; background-repeat: initial initial;">Submit</button><span class="nform_res" style="display: none;"></span></div>
</form>
</div>
<div class='nform_demo_cover'>
	<h3>Multi Column Layout</h3>
	<form class="nform bootstrap debut three label_line" action="javascript:submit_nform(7394);" ng-style="{width: con[0].fw, borderRadius: con[0].fr, MozBorderRadius: con[0].fr, WebkitBorderRadius: con[0].fr, fontFamily: con[0].formfamily}" id="7394" style="border-top-left-radius: 6px; border-top-right-radius: 6px; border-bottom-right-radius: 6px; border-bottom-left-radius: 6px; font-family: 'Trebuchet MS';">
		<input type="hidden" class="form_id" val="2">

		<div id="fe_title" class="nform_li form_title debut" ng-style="{fontSize: con[0].ft_px, borderTopLeftRadius: con[0].fr, MozBorderTopLeftRadius: con[0].fr, WebkitBorderTopLeftRadius: con[0].fr, borderTopRightRadius: con[0].fr, MozBorderTopRightRadius: con[0].fr, WebkitBorderTopRightRadius: con[0].fr, color: con[0].ft_co, backgroundColor: con[0].ft_bg, fontFamily: con[0].tfamily, fontWeight: con[0].tbold}" style="font-size: 32px; border-top-left-radius: 6px; border-top-right-radius: 6px; color: rgb(134, 134, 134); background-color: rgb(240, 240, 240); font-weight: normal;">Awesome Layout</div>


		<ul class="form_ul clearfix debut" style="">
			<!-- ngRepeat: el in build --><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_0" class="nform_li inline2">
			<div compile="el.el_f"><span class="cap_cover "><span class="cap1 subl" ng-style="{ fontSize: con[0].lfs, color: con[0].lfc}" style="font-size: 15px;">First Name<span class="show_1">*</span></span><span class="cap2 subl" ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">only alphabets</span></span><span class="input_cover text_cover ng-scope"><input type="text" ng-style="{width: el.wid}" name="First Name_text_alphabets_1_0_60_field0" style="width: 100%;"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field0 valid_show" style="display: none;"></span></span></div>
		</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_1" class="nform_li inline2">
		<div compile="el.el_f"><span class="cap_cover "><span class="cap1 subl" ng-style="{ fontSize: con[0].lfs, color: con[0].lfc}" style="font-size: 15px;">Last Name<span class="show_0">*</span></span><span class="cap2 subl" ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">only alphabets</span></span><span class="input_cover text_cover ng-scope"><input type="text" ng-style="{width: el.wid}" name="Last Name_text_alphabets_0_0_60_field1" style="width: 100%;"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field1 valid_show" style="display: none;"></span></span></div>
	</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_2" class="nform_li inline3">
	<div compile="el.el_f"><span class="cap_cover "><span class="cap1 subl" ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 15px;">Country<span class="show_0">*</span></span><span class="cap2 subl" ng-bind="el.dcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">select your country</span></span><span class="input_cover text_cover ng-scope"><select ng-style="{ width: el.widdr }" name="Country_dropdown__0___field2" style="width: 112%;"><!-- ngRepeat: opt in option[10].Drop --><option ng-repeat="opt in option[10].Drop" class="ng-scope ng-binding" value="Country One">Country One</option><option ng-repeat="opt in option[10].Drop" class="ng-scope ng-binding" value="Country Two">Country Two</option><option ng-repeat="opt in option[10].Drop" class="ng-scope ng-binding" value="Country Three">Country Three</option></select><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field2 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_3" class="nform_li inline3">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 subl" ng-style="{ fontSize: con[0].lfs, color: con[0].lfc}" style="font-size: 15px;">State<span class="show_0">*</span></span><span class="cap2 subl" ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">initials will do</span></span><span class="input_cover text_cover ng-scope"><input type="text" ng-style="{width: el.wid}" name="State_text__0_0_60_field3" style="width: 100%;"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field3 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_4" class="nform_li inline3">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 subl" ng-style="{ fontSize: con[0].lfs, color: con[0].lfc}" style="font-size: 15px;">City<span class="show_0">*</span></span><span class="cap2 subl" ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">no initials here</span></span><span class="input_cover text_cover ng-scope"><input type="text" ng-style="{width: el.wid}" name="City_text__0_0_60_field4" style="width: 100%;"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field4 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_5" class="nform_li">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 subl" ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 15px;">Comments<span class="show_0">*</span></span><span class="cap2 subl" ng-bind="el.pcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">further details</span></span><span class="input_cover text_cover ng-scope"><textarea rows="3" ng-style="{ width: el.wid }" name="Comments_para__0_0_60_field5" style="width: 100%;"></textarea><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field5 valid_show" style="display: none;"></span></span></div>
</li>
</ul>
<div id="fe_submit" class="nform_li form_submit" style="position: relative; display: block">

	<button type="submit" class="submit_button nform_btn custom" ng-style="{background: con[0].sco, fontSize: con[0].sfs,  marginLeft: con[0].lp,  marginTop: con[0].tp,  marginBottom: con[0].bp,  marginRight: con[0].rp,  paddingTop: con[0].spad1,  paddingBottom: con[0].spad1,  paddingRight: con[0].spad2,  paddingLeft: con[0].spad2,  borderRadius: con[0].curve,  MozBorderRadius: con[0].curve,  WebkitBorderRadius: con[0].curve, fontFamily: con[0].sfamily, fontWeight: con[0].sbold, color: con[0].sbfco}" data-loading-text="Sending ..." style="font-size: 16px; margin-left: 0px; margin-top: 20px; margin-bottom: 20px; padding: 15px 44px; font-weight: bold;">Submit</button>
	<br>
	<span style="text-align: center; display: block">
		<a class="ref_link" ng-href="http://codecanyon.net/item/nforms-wordpress-form-builder/4104704?ref=nCrafts" compile="con[0].rlink" target="_blank" href=""></a>
	</span>

	<span class="nform_res" style="display: none;"></span></div>
</form>
</div>
<div class='nform_demo_cover left'>
	<h3>Dark</h3>
	<form class="nform bootstrap carbon one label_line" action="javascript:submit_nform(12647);" ng-style="{width: con[0].fw, borderRadius: con[0].fr, MozBorderRadius: con[0].fr, WebkitBorderRadius: con[0].fr, fontFamily: con[0].formfamily}" style='width: 480px' id="12647">
		<input type="hidden" class="form_id" val="29">

		<div id="fe_title" class="nform_li form_title carbon" ng-style="{fontSize: con[0].ft_px, borderTopLeftRadius: con[0].fr, MozBorderTopLeftRadius: con[0].fr, WebkitBorderTopLeftRadius: con[0].fr, borderTopRightRadius: con[0].fr, MozBorderTopRightRadius: con[0].fr, WebkitBorderTopRightRadius: con[0].fr, color: con[0].ft_co, backgroundColor: con[0].ft_bg, fontFamily: con[0].tfamily, fontWeight: con[0].tbold}" style="font-size: 32px; color: rgb(255, 255, 255);">Talk to Us!</div>


		<ul class="form_ul carbon" style="">
			<!-- ngRepeat: el in build --><li ng-repeat="el in build" style="padding-bottom: 13px; padding-top: 13px;" id="fe_0" class="nform_li ng-scope">
			<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px; color: rgb(240, 240, 240);">Email<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.ecap2" ng-style="{fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(225, 225, 225);">how else do we get back to you?</span></span><span class="input_cover text_cover ng-scope"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }" style="color: rgb(201, 201, 201);"></span><span class="input-append"><input type="email" ng-style="{ width: el.wid2 }" name="Email_email_email_1___field0" style="width: 284px;"><span class="add-on"><i class="icon-envelope"></i></span></span><span class="field0 valid_show" style="display: none;"></span></span></div>
		</li><li ng-repeat="el in build" style="padding-bottom: 13px; padding-top: 13px;" id="fe_1" class="nform_li ng-scope">
		<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px; color: rgb(240, 240, 240);">Comments<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(225, 225, 225);">at least 10 characters</span></span><span class="input_cover text_cover ng-scope"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }" style="color: rgb(201, 201, 201);"></span><textarea rows="3" ng-style="{ width: el.wid }" name="Comments_para__1_10_500_field1" style="width: 310px;"></textarea><span class="field1 valid_show" style="display: none;"></span></span></div>
	</li><li ng-repeat="el in build" style="padding-bottom: 13px; padding-top: 13px;" id="fe_2" class="nform_li ng-scope nform_li_before">
	<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px; color: rgb(240, 240, 240);">Country<span class="show_0">*</span></span><span class="cap2 " ng-bind="el.dcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(225, 225, 225);">where are you from?</span></span><span class="input_cover text_cover ng-scope"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }" style="color: rgb(201, 201, 201);"></span><select ng-style="{ width: el.wid }" name="Country_dropdown__0___field2" style="width: 325px;"><!-- ngRepeat: opt in option[3].Drop --><option ng-repeat="opt in option[3].Drop" class="ng-scope ng-binding" value="USA">USA</option><option ng-repeat="opt in option[3].Drop" class="ng-scope ng-binding" value="UK">UK</option><option ng-repeat="opt in option[3].Drop" class="ng-scope ng-binding" value="Other">Other</option></select><span class="field2 valid_show" style="display: none;"></span></span></div>
</li>
</ul>
<div id="fe_submit" class="nform_li form_submit" style="position: relative; display: block"><button type="submit" class="submit_button nform_btn " ng-style="{background: con[0].sco, fontSize: con[0].sfs,  marginLeft: con[0].lp,  marginTop: con[0].tp,  marginBottom: con[0].bp,  marginRight: con[0].rp,  paddingTop: con[0].spad1,  paddingBottom: con[0].spad1,  paddingRight: con[0].spad2,  paddingLeft: con[0].spad2,  borderRadius: con[0].curve,  MozBorderRadius: con[0].curve,  WebkitBorderRadius: con[0].curve, fontFamily: con[0].sfamily, fontWeight: con[0].sbold, color: con[0].sbfco}" data-loading-text="Sending ..." style="background-color: rgb(74, 74, 74); font-size: 14px; margin-left: 20px; margin-top: 20px; margin-bottom: 20px; padding: 8px 28px; background-position: initial initial; background-repeat: initial initial;">Submit</button><span class="nform_res" style="display: none;"></span></div>
</form>
</div>

<div class='nform_demo_cover'>
	<h3>Popup Form</h3>

	<a href="#myModal" role="button" data-toggle="modal" id='mod' class='btn'>Click Here</a>

	<!-- Modal -->
	<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style='display: none'>
		<button type="button" class="close modal_close" data-dismiss="modal" aria-hidden="true">x</button>
		<div>


			<form class="nform bootstrap debut one transparent " action="javascript:submit_nform(18358);" ng-style="{width: con[0].fw, borderRadius: con[0].fr, MozBorderRadius: con[0].fr, WebkitBorderRadius: con[0].fr, fontFamily: con[0].formfamily}" id="18358" style="width: 440px; border-top-left-radius: 20px; border-top-right-radius: 20px; border-bottom-right-radius: 20px; border-bottom-left-radius: 20px; font-family: 'Trebuchet MS';">
				<input type="hidden" class="form_id" val="38">

				<div id="fe_title" class="nform_li form_title debut" ng-style="{fontSize: con[0].ft_px, borderTopLeftRadius: con[0].fr, MozBorderTopLeftRadius: con[0].fr, WebkitBorderTopLeftRadius: con[0].fr, borderTopRightRadius: con[0].fr, MozBorderTopRightRadius: con[0].fr, WebkitBorderTopRightRadius: con[0].fr, color: con[0].ft_co, backgroundColor: con[0].ft_bg, fontFamily: con[0].tfamily, fontWeight: con[0].tbold}" style="font-size: 32px; border-top-left-radius: 20px; border-top-right-radius: 20px; font-weight: normal;">Popup Form</div>


				<ul class="form_ul debut" style="">
					<!-- ngRepeat: el in build --><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px" id="fe_0" class="nform_li ng-scope">
					<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc}" style="font-size: 14px; color: rgb(117, 117, 117);">Name<span class="show_0">*</span></span><span class="cap2 " ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(148, 148, 148);">full name here</span></span><span class="input_cover text_cover ng-scope"><input type="text" ng-style="{width: el.wid}" name="Name_text__0_0_60_field0" style="width: 220px;"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field0 valid_show"></span></span></div>
				</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px" id="fe_1" class="nform_li ng-scope">
				<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px; color: rgb(117, 117, 117);">Comments<span class="show_0">*</span></span><span class="cap2 " ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(148, 148, 148);">further details</span></span><span class="input_cover text_cover ng-scope"><textarea rows="3" ng-style="{ width: el.wid }" name="Comments_para__0_0_60_field1" style="width: 220px;"></textarea><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field1 valid_show"></span></span></div>
			</li>
		</ul>
		<div id="fe_submit" class="nform_li form_submit nform_li_before" style="position: relative; display: block"><button type="submit" class="submit_button nform_btn custom" ng-style="{background: con[0].sco, fontSize: con[0].sfs,  marginLeft: con[0].lp,  marginTop: con[0].tp,  marginBottom: con[0].bp,  marginRight: con[0].rp,  paddingTop: con[0].spad1,  paddingBottom: con[0].spad1,  paddingRight: con[0].spad2,  paddingLeft: con[0].spad2,  borderRadius: con[0].curve,  MozBorderRadius: con[0].curve,  WebkitBorderRadius: con[0].curve, fontFamily: con[0].sfamily, fontWeight: con[0].sbold, color: con[0].sbfco}" data-loading-text="Sending ..." style="background-color: rgb(218, 218, 218); font-size: 14px; margin-left: 0px; margin-top: 20px; margin-bottom: 30px; padding: 8px 32px; font-weight: bold; background-position: initial initial; background-repeat: initial initial;">Submit</button><span class="nform_res" style="display: none;"></span></div>
	</form>

</div>
</div>

</div>




<h2 class='h2' id='embed'>Embed Stuff</h2>
<p style='font-size: 16px'>If the embedded Youtube video, or Google Maps does not appear, remove the CodeCanyon frame.</p>
<div class='nform_demo_cover left'>
	<h3>Add Google Maps</h3>
	<form class="nform bootstrap none one  " action="javascript:submit_nform(7337);" ng-style="{width: con[0].fw, borderRadius: con[0].fr, MozBorderRadius: con[0].fr, WebkitBorderRadius: con[0].fr}" id="7337" style="border-top-left-radius: 10px; border-top-right-radius: 10px; border-bottom-right-radius: 10px; border-bottom-left-radius: 10px;">
		<input type="hidden" class="form_id" val="33">

		<div id="fe_title" class="nform_li form_title none" ng-style="{fontSize: con[0].ft_px, borderTopLeftRadius: con[0].fr, MozBorderTopLeftRadius: con[0].fr, WebkitBorderTopLeftRadius: con[0].fr, borderTopRightRadius: con[0].fr, MozBorderTopRightRadius: con[0].fr, WebkitBorderTopRightRadius: con[0].fr, color: con[0].ft_co, backgroundColor: con[0].ft_bg}" style="font-size: 26px; border-top-left-radius: 10px; border-top-right-radius: 10px; color: rgb(41, 154, 81); background-color: rgb(248, 248, 248);">Store Feedback</div>


		<ul class="form_ul none" style="">
			<!-- ngRepeat: el in build --><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px; position: relative;" id="fe_0" class="nform_li ng-scope">
			<div compile="el.el_f"><span ng-style="{ marginBottom: el.divspa, marginTop: el.divspa, fontSize: el.divfs, color: el.divfc }" compile="el.divcap2" style="display: block; position: relative; margin-bottom: 0px; margin-top: 0px; font-size: 14px; color: rgb(102, 102, 102);" class="ng-scope"></span></div>
		</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_1" class="nform_li ng-scope">
		<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc}" style="font-size: 14px; color: rgb(41, 154, 81);">Name<span class="show_0">*</span></span><span class="cap2 " ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">full name here</span></span><span class="input_cover text_cover ng-scope"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><input type="text" ng-style="{width: el.wid}" name="Name_text__0_0_60_field1" style="width: 150px;"><span class="field1 valid_show" style="display: none;"></span></span></div>
	</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px; position: relative;" id="fe_2" class="nform_li ng-scope">
	<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px; color: rgb(41, 154, 81);">Email<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.ecap2" ng-style="{fontSize: con[0].slfs, color: con[0].slfc }">we'll get back</span></span><span class="input_cover text_cover ng-scope"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="input-append"><input type="email" ng-style="{ width: el.wid2 }" name="Email_email_email_1___field2" style="width: 124px;"><span class="add-on"><i class="icon-envelope"></i></span></span><span class="field2 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_3" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px; color: rgb(41, 154, 81);">Feedback<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">like it?</span></span><span class="input_cover text_cover ng-scope"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><textarea rows="3" ng-style="{ width: el.wid }" name="Feedback_para__1_0_600_field3" style="width: 150px;"></textarea><span class="field3 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_4" class="nform_li ng-scope">
<div compile="el.el_f"><span ng-style="{ marginBottom: el.divspa, marginTop: el.divspa, fontSize: el.divfs, color: el.divfc }" compile="el.divcap2" style="display: block; position: relative; margin-bottom: 0px; margin-top: 0px; font-size: 13px; color: rgb(41, 154, 81);" class="ng-scope"><div style="position: absolute; right: 8px; top: -130px;" class="ng-scope">89/90 D Lincoln Ave<br>New York, NY<br>(212) 334-2534<br><br>abc@example.com</div></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_5" class="nform_li ng-scope nform_li_before">
<div compile="el.el_f"><div class="divider ng-scope" ng-style="{ borderTopWidth: el.divwid, borderTopColor: el.divcol, marginBottom: el.divspa, marginTop: el.divspa }" style="border-top-style: solid; border-top-width: 1px; border-top-color: rgb(223, 223, 223); margin-bottom: 0px; margin-top: 0px;"><span class="div_text" ng-style="{ marginTop: el.divtop }" style="margin-top: -10px;"><span class="div_text2 ng-binding" ng-style="{ marginLeft: el.divlef, fontSize: el.divfs, color: el.divfc }" style="margin-left: 40px; font-size: 16px; color: rgb(41, 154, 81);">Or, just drop by and say hello</span></span></div></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_6" class="nform_li ng-scope">
<div compile="el.el_f"><span ng-style="{ marginBottom: el.divspa, marginTop: el.divspa, fontSize: el.divfs, color: el.divfc }" class="div_text2 ng-scope" compile="el.divcap2" style="display: block; margin-bottom: 0px; margin-top: 0px; font-size: 14px; color: rgb(102, 102, 102);"><iframe style="padding-left: 10px" width="100%" height="250" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.in/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=new+york&amp;aq=&amp;sll=18.815427,76.775144&amp;sspn=12.747161,24.960937&amp;ie=UTF8&amp;hq=&amp;hnear=New+York,+United+States&amp;ll=40.714353,-74.005973&amp;spn=0.019973,0.048752&amp;t=m&amp;z=14&amp;output=embed" class="ng-scope"></iframe></span></div>
</li>
</ul>
<div id="fe_submit" class="nform_li form_submit" style="position: relative; display: block"><button type="submit" class="submit_button nform_btn" ng-style="{background: con[0].sco, fontSize: con[0].sfs,  marginLeft: con[0].lp,  marginTop: con[0].tp,  marginBottom: con[0].bp,  marginRight: con[0].rp,  paddingTop: con[0].spad1,  paddingBottom: con[0].spad1,  paddingRight: con[0].spad2,  paddingLeft: con[0].spad2,  borderRadius: con[0].curve,  MozBorderRadius: con[0].curve,  WebkitBorderRadius: con[0].curve}" data-loading-text="Sending ..." style="background-color: rgb(41, 154, 81); font-size: 14px; margin-left: 20px; margin-top: 10px; margin-bottom: 20px; padding: 12px 22px; background-position: initial initial; background-repeat: initial initial;">Submit</button><span class="nform_res" style="display: none;"></span></div>
</form>		</div>
<div class='nform_demo_cover'>
	<h3>Add Videos</h3>
	<form class="nform bootstrap satin one  " action="javascript:submit_nform(448);" ng-style="{width: con[0].fw, borderRadius: con[0].fr, MozBorderRadius: con[0].fr, WebkitBorderRadius: con[0].fr, fontFamily: con[0].formfamily}" id="448" style="border-top-left-radius: 5px; border-top-right-radius: 5px; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px; font-family: 'Trebuchet MS';">
		<input type="hidden" class="form_id" val="34">

		<div id="fe_title" class="nform_li form_title satin" ng-style="{fontSize: con[0].ft_px, borderTopLeftRadius: con[0].fr, MozBorderTopLeftRadius: con[0].fr, WebkitBorderTopLeftRadius: con[0].fr, borderTopRightRadius: con[0].fr, MozBorderTopRightRadius: con[0].fr, WebkitBorderTopRightRadius: con[0].fr, color: con[0].ft_co, backgroundColor: con[0].ft_bg, fontFamily: con[0].tfamily, fontWeight: con[0].tbold}" style="font-size: 28px; border-top-left-radius: 5px; border-top-right-radius: 5px; color: rgb(129, 129, 129); font-weight: normal;">Rate this Video</div>


		<ul class="form_ul satin" style="">
			<!-- ngRepeat: el in build --><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_0" class="nform_li ng-scope">
			<div compile="el.el_f"><span ng-style="{ marginBottom: el.divspa, marginTop: el.divspa, fontSize: el.divfs, color: el.divfc }" compile="el.divcap2" style="display: block; position: relative; margin-bottom: 0px; margin-top: 0px; font-size: 14px; color: rgb(102, 102, 102);" class="ng-scope"><div style="padding-left: 3%; padding-right: 3%" class="ng-scope"><iframe width="100%" height="315" src="http://www.youtube.com/embed/_OBlgSz8sSM?rel=0" frameborder="0" allowfullscreen=""></iframe></div></span></div>
		</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_1" class="nform_li ng-scope nform_li_before">
		<div compile="el.el_f"><div class="divider ng-scope" ng-style="{ borderTopWidth: el.divwid, borderTopColor: el.divcol, marginBottom: el.divspa, marginTop: el.divspa }" style="border-top-style: solid; border-top-width: 1px; border-top-color: rgb(205, 205, 205); margin-bottom: 30px; margin-top: 30px;"><span class="div_text" ng-style="{ marginTop: el.divtop }" style="margin-top: -10px;"><span class="div_text2 ng-binding" ng-style="{ marginLeft: el.divlef, fontSize: el.divfs, color: el.divfc }" style="margin-left: 10%; font-size: 16px; color: rgb(105, 105, 105);">So, did you like the video?</span></span></div></div>
	</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_2" class="nform_li ng-scope">
	<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px;">Email<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.ecap2" ng-style="{fontSize: con[0].slfs, color: con[0].slfc }">can't leave this empty</span></span><span class="input_cover text_cover ng-scope"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="input-append"><input type="email" ng-style="{ width: el.wid2 }" name="Email_email_email_1___field2" style="width: 194px;"><span class="add-on"><i class="icon-envelope"></i></span></span><span class="field2 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_3" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px;">Rating<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.rcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">how funny was it?</span></span><span class="input_cover ng-scope"><span class="box_cover lines"><!-- ngRepeat: opt in option[5].Drop --><label class="label_radio ng-scope ng-binding" ng-style="{width: el.wid}" ng-repeat="opt in option[5].Drop" for="radio50" style="width: 220px;"><input type="radio" class="label_radio" value="Was it supposed to be funny?" id="radio50" name="Rating_radio__1___field3">Was it supposed to be funny?</label><label class="label_radio ng-scope ng-binding" ng-style="{width: el.wid}" ng-repeat="opt in option[5].Drop" for="radio51" style="width: 220px;"><input type="radio" class="label_radio" value="Hm... just ok" id="radio51" name="Rating_radio__1___field3">Hm... just ok</label><label class="label_radio ng-scope ng-binding" ng-style="{width: el.wid}" ng-repeat="opt in option[5].Drop" for="radio52" style="width: 220px;"><input type="radio" class="label_radio" value="Yeah, liked it" id="radio52" name="Rating_radio__1___field3">Yeah, liked it</label><label class="label_radio ng-scope ng-binding" ng-style="{width: el.wid}" ng-repeat="opt in option[5].Drop" for="radio53" style="width: 220px;"><input type="radio" class="label_radio" value="Hilarious!" id="radio53" name="Rating_radio__1___field3">Hilarious!</label><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field3 valid_show" style="display: none;"></span></span></span></div>
</li>
</ul>
<div id="fe_submit" class="nform_li form_submit" style="position: relative; display: block"><button type="submit" class="submit_button nform_btn " ng-style="{background: con[0].sco, fontSize: con[0].sfs,  marginLeft: con[0].lp,  marginTop: con[0].tp,  marginBottom: con[0].bp,  marginRight: con[0].rp,  paddingTop: con[0].spad1,  paddingBottom: con[0].spad1,  paddingRight: con[0].spad2,  paddingLeft: con[0].spad2,  borderRadius: con[0].curve,  MozBorderRadius: con[0].curve,  WebkitBorderRadius: con[0].curve, fontFamily: con[0].sfamily, fontWeight: con[0].sbold, color: con[0].sbfco}" data-loading-text="Sending ..." style="background-color: rgb(152, 173, 224); font-size: 21px; margin-left: 0px; margin-top: 10px; margin-bottom: 25px; padding: 14px 38%; font-weight: bold; background-position: initial initial; background-repeat: initial initial;">Submit</button><span class="nform_res" style="display: none;"></span></div>
</form>
</div>


<h2 class='h2' id='job'>More Examples</h2>
<div class='nform_demo_cover left'>
	<h3>Job Application</h3>
	<form class="nform bootstrap none one  " action="javascript:submit_nform(224162707);" ng-style="{width: con[0].fw, borderRadius: con[0].fr, MozBorderRadius: con[0].fr, WebkitBorderRadius: con[0].fr, fontFamily: con[0].formfamily}" id="224162707" style="border-top-left-radius: 10px; border-top-right-radius: 10px; border-bottom-right-radius: 10px; border-bottom-left-radius: 10px; font-family: 'Trebuchet MS';">
		<input type="hidden" class="form_id" val="35">

		<div id="fe_title" class="nform_li form_title none" ng-style="{fontSize: con[0].ft_px, borderTopLeftRadius: con[0].fr, MozBorderTopLeftRadius: con[0].fr, WebkitBorderTopLeftRadius: con[0].fr, borderTopRightRadius: con[0].fr, MozBorderTopRightRadius: con[0].fr, WebkitBorderTopRightRadius: con[0].fr, color: con[0].ft_co, backgroundColor: con[0].ft_bg, fontFamily: con[0].tfamily, fontWeight: con[0].tbold}" style="font-size: 28px; border-top-left-radius: 10px; border-top-right-radius: 10px; color: rgb(115, 115, 115); font-weight: normal;">Job Application</div>


		<ul class="form_ul none" style="">
			<!-- ngRepeat: el in build --><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_0" class="nform_li ng-scope">
			<div compile="el.el_f"><div class="divider ng-scope" ng-style="{ borderTopWidth: el.divwid, borderTopColor: el.divcol, marginBottom: el.divspa, marginTop: el.divspa }" style="border-top-style: solid; border-top-width: 1px; border-top-color: rgb(204, 204, 204); margin-bottom: 20px; margin-top: 20px;"><span class="div_text" ng-style="{ marginTop: el.divtop }" style="margin-top: -12px;"><span class="div_text2 ng-binding" ng-style="{ marginLeft: el.divlef, fontSize: el.divfs, color: el.divfc }" style="margin-left: 65%; font-size: 16px; color: rgb(129, 129, 129);">About Yourself</span></span></div></div>
		</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_1" class="nform_li ng-scope">
		<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc}" style="font-size: 14px; color: rgb(115, 115, 115);">Name<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(0, 141, 196);">full name here</span></span><span class="input_cover text_cover ng-scope"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><input type="text" ng-style="{width: el.wid}" name="Name_text__1_0_60_field1" style="width: 220px;"><span class="field1 valid_show" style="display: none;"></span></span></div>
	</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_2" class="nform_li ng-scope">
	<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px; color: rgb(115, 115, 115);">E-mail<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.ecap2" ng-style="{fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(0, 141, 196);"></span></span><span class="input_cover text_cover ng-scope"><span class="input-append"><input type="email" ng-style="{ width: el.wid2 }" name="E-mail_email_email_1___field2" style="width: 194px;"><span class="add-on"><i class="icon-envelope"></i></span></span><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field2 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_3" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px; color: rgb(115, 115, 115);">Date of Birth<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.dtcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(0, 141, 196);"></span></span><span class="input_cover text_cover ng-scope"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="input-append"><input type="text" ng-style="{ width: el.wid2 }" class="datepickermdy" name="Date of Birth_date_date_1___field3" style="width: 194px;"><span class="add-on"><i class="icon-calendar"></i></span></span><span class="field3 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_4" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px; color: rgb(115, 115, 115);">Country<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.dcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(0, 141, 196);">of residence</span></span><span class="input_cover ng-scope"><select ng-style="{ width: el.wid }" name="Country_dropdown__1___field4" style="width: 234px;"><!-- ngRepeat: opt in option[31].Drop --><option ng-repeat="opt in option[31].Drop" class="ng-scope ng-binding" value="USA">USA</option><option ng-repeat="opt in option[31].Drop" class="ng-scope ng-binding" value="UK">UK</option><option ng-repeat="opt in option[31].Drop" class="ng-scope ng-binding" value="Others">Others</option></select><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field4 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_5" class="nform_li ng-scope">
<div compile="el.el_f"><span ng-style="{ marginBottom: el.divspa, marginTop: el.divspa, fontSize: el.divfs, color: el.divfc }" compile="el.divcap2" style="display: block; position: relative; margin-bottom: 0px; margin-top: 0px; font-size: 14px; color: rgb(102, 102, 102);" class="ng-scope"></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_6" class="nform_li ng-scope">
<div compile="el.el_f"><div class="divider ng-scope" ng-style="{ borderTopWidth: el.divwid, borderTopColor: el.divcol, marginBottom: el.divspa, marginTop: el.divspa }" style="border-top-style: solid; border-top-width: 1px; border-top-color: rgb(204, 204, 204); margin-bottom: 20px; margin-top: 20px;"><span class="div_text" ng-style="{ marginTop: el.divtop }" style="margin-top: -12px;"><span class="div_text2 ng-binding" ng-style="{ marginLeft: el.divlef, fontSize: el.divfs, color: el.divfc }" style="margin-left: 10%; font-size: 16px; color: rgb(129, 129, 129);">Current Employment</span></span></div></div>
</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_7" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px; color: rgb(115, 115, 115);">Employed?<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.rcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(0, 141, 196);"></span></span><span class="input_cover ng-scope"><span class="box_cover lines"><!-- ngRepeat: opt in option[30].Drop --><label class="label_radio ng-scope ng-binding" ng-repeat="opt in option[30].Drop" for="radio300"><input type="radio" class="label_radio" value="Working full time" id="radio300" name="Employed?_radio__1___field7">Working full time</label><label class="label_radio ng-scope ng-binding" ng-repeat="opt in option[30].Drop" for="radio301"><input type="radio" class="label_radio" value="Working part-time" id="radio301" name="Employed?_radio__1___field7">Working part-time</label><label class="label_radio ng-scope ng-binding" ng-repeat="opt in option[30].Drop" for="radio302"><input type="radio" class="label_radio" value="Not currently employed" id="radio302" name="Employed?_radio__1___field7">Not currently employed</label><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field7 valid_show" style="display: none;"></span></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_8" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px; color: rgb(115, 115, 115);">Relocation<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.rcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(0, 141, 196);">open to relocation?</span></span><span class="input_cover ng-scope"><span class="box_cover "><!-- ngRepeat: opt in option[32].Drop --><label class="label_radio ng-scope ng-binding" ng-repeat="opt in option[32].Drop" for="radio320"><input type="radio" class="label_radio" value="Yes" id="radio320" name="Relocation_radio__1___field8">Yes</label><label class="label_radio ng-scope ng-binding" ng-repeat="opt in option[32].Drop" for="radio321"><input type="radio" class="label_radio" value="Depends" id="radio321" name="Relocation_radio__1___field8">Depends</label><label class="label_radio ng-scope ng-binding" ng-repeat="opt in option[32].Drop" for="radio322"><input type="radio" class="label_radio" value="No" id="radio322" name="Relocation_radio__1___field8">No</label><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field8 valid_show" style="display: none;"></span></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_9" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc}" style="font-size: 14px; color: rgb(115, 115, 115);">Name of Employer<span class="show_0">*</span></span><span class="cap2 " ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(0, 141, 196);">current, or last</span></span><span class="input_cover text_cover ng-scope"><input type="text" ng-style="{width: el.wid}" name="Name of Employer_text__0_0_60_field9" style="width: 220px;"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field9 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_10" class="nform_li ng-scope">
<div compile="el.el_f"><span ng-style="{ marginBottom: el.divspa, marginTop: el.divspa, fontSize: el.divfs, color: el.divfc }" compile="el.divcap2" style="display: block; position: relative; margin-bottom: 0px; margin-top: 0px; font-size: 14px; color: rgb(102, 102, 102);" class="ng-scope"></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_11" class="nform_li ng-scope">
<div compile="el.el_f"><div class="divider ng-scope" ng-style="{ borderTopWidth: el.divwid, borderTopColor: el.divcol, marginBottom: el.divspa, marginTop: el.divspa }" style="border-top-style: solid; border-top-width: 1px; border-top-color: rgb(204, 204, 204); margin-bottom: 20px; margin-top: 20px;"><span class="div_text" ng-style="{ marginTop: el.divtop }" style="margin-top: -12px;"><span class="div_text2 ng-binding" ng-style="{ marginLeft: el.divlef, fontSize: el.divfs, color: el.divfc }" style="margin-left: 65%; font-size: 16px; color: rgb(129, 129, 129);">Application</span></span></div></div>
</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_12" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px; color: rgb(115, 115, 115);">Position<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.dcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(0, 141, 196);">applied for</span></span><span class="input_cover ng-scope"><select ng-style="{ width: el.wid }" name="Position_dropdown__1___field12" style="width: 220px;"><!-- ngRepeat: opt in option[38].Drop --><option ng-repeat="opt in option[38].Drop" class="ng-scope ng-binding" value="Analyst">Analyst</option><option ng-repeat="opt in option[38].Drop" class="ng-scope ng-binding" value="Senior Analyst">Senior Analyst</option><option ng-repeat="opt in option[38].Drop" class="ng-scope ng-binding" value="Manager">Manager</option><option ng-repeat="opt in option[38].Drop" class="ng-scope ng-binding" value="Client Manager">Client Manager</option></select><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field12 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_13" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px; color: rgb(115, 115, 115);">Pay<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.slcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(0, 141, 196);">your expectations</span></span><span class="input_cover ng-scope"><span class="box_cover "><!-- ngRepeat: opt in option[39].Drop --><div ng-repeat="opt in option[39].Drop" class="ng-scope"><span class="slider_txt ng-binding">Base Pay ($ p.a.)</span><span id="slider_13_0_30000_120000_val" class="slider_val"></span><input type="hidden" id="slider_13_0_30000_120000_val2" name="Pay-Base Pay ($ p.a.)_slider-range__1___field13"><div class="slider-range ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" ng-style="{ width: el.wid }" id="slider_13_0_30000_120000" slider="" style="width: 220px;" aria-disabled="false"><div class="ui-slider-range ui-widget-header" style="left: 0%; width: 6.666666666666667%;"></div><a class="ui-slider-handle ui-state-default ui-corner-all" href="#" style="left: 0%;"></a><a class="ui-slider-handle ui-state-default ui-corner-all" href="#" style="left: 6.666666666666667%;"></a></div></div><div ng-repeat="opt in option[39].Drop" class="ng-scope"><span class="slider_txt ng-binding">Benefits ($ p.a.)</span><span id="slider_13_1_10000_40000_val" class="slider_val"></span><input type="hidden" id="slider_13_1_10000_40000_val2" name="Pay-Benefits ($ p.a.)_slider-range__1___field13"><div class="slider-range ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" ng-style="{ width: el.wid }" id="slider_13_1_10000_40000" slider="" style="width: 220px;" aria-disabled="false"><div class="ui-slider-range ui-widget-header" style="left: 0%; width: 6.666666666666667%;"></div><a class="ui-slider-handle ui-state-default ui-corner-all" href="#" style="left: 0%;"></a><a class="ui-slider-handle ui-state-default ui-corner-all" href="#" style="left: 6.666666666666667%;"></a></div></div><span class="inst sld ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field13 valid_show" style="display: none;"></span></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_14" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px; color: rgb(115, 115, 115);">Skills<span class="show_0">*</span></span><span class="cap2 " ng-bind="el.ccap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(0, 141, 196);">don't fake it</span></span><span class="input_cover ng-scope"><span class="box_cover lines"><!-- ngRepeat: opt in option[44].Drop --><label class="label_check ng-scope ng-binding" ng-style="{width: el.wid}" ng-repeat="opt in option[44].Drop" for="check440" style=""><input type="checkbox" class="label_check" value="Financial Markets" id="check440" name="Skills_check__0___field14">Financial Markets</label><label class="label_check ng-scope ng-binding" ng-style="{width: el.wid}" ng-repeat="opt in option[44].Drop" for="check441" style=""><input type="checkbox" class="label_check" value="Client Management" id="check441" name="Skills_check__0___field14">Client Management</label><label class="label_check ng-scope ng-binding" ng-style="{width: el.wid}" ng-repeat="opt in option[44].Drop" for="check442" style=""><input type="checkbox" class="label_check" value="Project Management" id="check442" name="Skills_check__0___field14">Project Management</label><label class="label_check ng-scope ng-binding" ng-style="{width: el.wid}" ng-repeat="opt in option[44].Drop" for="check443" style=""><input type="checkbox" class="label_check" value="International Taxation" id="check443" name="Skills_check__0___field14">International Taxation</label><label class="label_check ng-scope ng-binding" ng-style="{width: el.wid}" ng-repeat="opt in option[44].Drop" for="check444" style=""><input type="checkbox" class="label_check" value="Asset Management" id="check444" name="Skills_check__0___field14">Asset Management</label><label class="label_check ng-scope ng-binding" ng-style="{width: el.wid}" ng-repeat="opt in option[44].Drop" for="check445" style=""><input type="checkbox" class="label_check" value="Private Equity" id="check445" name="Skills_check__0___field14">Private Equity</label><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field14 valid_show" style="display: none;"></span></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 10px; padding-top: 10px;" id="fe_15" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 " ng-style="{ fontSize: con[0].lfs, color: con[0].lfc}" style="font-size: 14px; color: rgb(115, 115, 115);">Upload CV<span class="show_1">*</span></span><span class="cap2 " ng-bind="el.ucap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }" style="color: rgb(0, 141, 196);">we prefer .pdf</span></span><span class="input_cover upload_input_cover ng-scope"><span class="btn btn-success fileupload-cover"><i class="icon-arrow-up icon-white"></i> <span>Upload File</span><input class="fileupload" type="file" ng-style="{width: el.wid}" data-url="file-upload/server/php/" name="files[]" style="width: 220px;"></span><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }"></span><span class="field15 valid_show" style="display: none;"></span><input type="hidden" class="upload_hidden" name="Upload CV_upload_file_1___field15" value="0"><ul class="upload_ul"></ul></span></div>
</li>
</ul>
<div id="fe_submit" class="nform_li form_submit" style="position: relative; display: block"><button type="submit" class="submit_button nform_btn custom" ng-style="{background: con[0].sco, fontSize: con[0].sfs,  marginLeft: con[0].lp,  marginTop: con[0].tp,  marginBottom: con[0].bp,  marginRight: con[0].rp,  paddingTop: con[0].spad1,  paddingBottom: con[0].spad1,  paddingRight: con[0].spad2,  paddingLeft: con[0].spad2,  borderRadius: con[0].curve,  MozBorderRadius: con[0].curve,  WebkitBorderRadius: con[0].curve, fontFamily: con[0].sfamily, fontWeight: con[0].sbold, color: con[0].sbfco}" data-loading-text="Sending ..." style="font-size: 18px; margin-top: 20px; margin-bottom: 30px; padding: 12px 36px; font-family: 'Trebuchet MS'; font-weight: bold;">Submit</button><span class="nform_res" style="display: none;"></span></div>
</form>	</div>


<div class='nform_demo_cover'>
	<h3>Booking</h3>


	<form class="nform bootstrap debut one  " action="javascript:submit_nform(28409);" ng-style="{width: con[0].fw, borderRadius: con[0].fr, MozBorderRadius: con[0].fr, WebkitBorderRadius: con[0].fr, fontFamily: con[0].formfamily}" id="28409" style="width: 540px; font-family: 'Times New Roman';">
		<input type="hidden" class="form_id" val="36">

		<div id="fe_title" class="nform_li form_title debut" ng-style="{fontSize: con[0].ft_px, borderTopLeftRadius: con[0].fr, MozBorderTopLeftRadius: con[0].fr, WebkitBorderTopLeftRadius: con[0].fr, borderTopRightRadius: con[0].fr, MozBorderTopRightRadius: con[0].fr, WebkitBorderTopRightRadius: con[0].fr, color: con[0].ft_co, backgroundColor: con[0].ft_bg, fontFamily: con[0].tfamily, fontWeight: con[0].tbold}" style="font-size: 32px; font-weight: normal;"></div>


		<ul class="form_ul debut" style="">
			<!-- ngRepeat: el in build --><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_0" class="nform_li ng-scope">
			<div compile="el.el_f"><span ng-style="{ marginBottom: el.divspa, marginTop: el.divspa, fontSize: el.divfs, color: el.divfc }" compile="el.divcap2" style="display: block; position: relative; font-size: 14px; color: rgb(102, 102, 102);" class="ng-scope"><div style=" text-align: center; width: 70%; margin-left: 15%; font-family: &quot;Times New Roman&quot;" class="ng-scope"><strong>The London Hotel</strong><br>8 - 12, Cooper's Row<br>London<br>EC3N 2BQ</div></span></div>
		</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_1" class="nform_li ng-scope">
		<div compile="el.el_f"><span ng-style="{ marginBottom: el.divspa, marginTop: el.divspa, fontSize: el.divfs, color: el.divfc, fontFamily: el.family }" compile="el.divcap2" style="display: block; position: relative; margin-bottom: 20px; margin-top: 20px; font-size: 14px; color: rgb(102, 102, 102);" class="ng-scope"><div style=" text-align: center; width: 80%; margin-left: 10%; font-family: &quot;Times New Roman&quot;" class="ng-scope">Booking Details<hr></div></span></div>
	</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_2" class="nform_li ng-scope">
	<div compile="el.el_f"><span class="cap_cover "><span class="cap1 subl" ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px;">Arrival Date<span class="show_1">*</span></span><span class="cap2 subl" ng-bind="el.dtcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }"></span></span><span class="input_cover text_cover ng-scope"><span class="input-append"><input type="text" ng-style="{ width: el.wid2 }" class="datepickermdy" name="Arrival Date_date_date_1___field2" style="width: 194px;"><span class="add-on"><i class="icon-calendar"></i></span></span><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }" style="font-size: 13px;"></span><span class="field2 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_3" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 subl" ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px;">Arrival Time<span class="show_0">*</span></span><span class="cap2 subl" ng-bind="el.tcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }"></span></span><span class="input-append ng-scope"><input type="time" ng-style="{ width: el.widt }" name="Arrival Time_time__0___field3" style="width: 194px;"><span class="add-on"><i class="icon-time"></i></span></span><span class="input_cover text_cover ng-scope"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }" style="font-size: 13px;"></span><span class="field3 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_4" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 subl" ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px;">Room Type<span class="show_1">*</span></span><span class="cap2 subl" ng-bind="el.rcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }"></span></span><span class="input_cover ng-scope"><span class="box_cover "><!-- ngRepeat: opt in option[15].Drop --><label class="label_radio ng-scope ng-binding" ng-style="{width: el.widcr}" ng-repeat="opt in option[15].Drop" for="radio150" style=""><input type="radio" class="label_radio" value="Standard" id="radio150" name="Room Type_radio__1___field4">Standard</label><label class="label_radio ng-scope ng-binding" ng-style="{width: el.widcr}" ng-repeat="opt in option[15].Drop" for="radio151" style=""><input type="radio" class="label_radio" value="Deluxe" id="radio151" name="Room Type_radio__1___field4">Deluxe</label><label class="label_radio ng-scope ng-binding" ng-style="{width: el.widcr}" ng-repeat="opt in option[15].Drop" for="radio152" style=""><input type="radio" class="label_radio" value="Suite" id="radio152" name="Room Type_radio__1___field4">Suite</label><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }" style="font-size: 13px;"></span><span class="field4 valid_show" style="display: none;"></span></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_5" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 subl" ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px;">Other Details<span class="show_1">*</span></span><span class="cap2 subl" ng-bind="el.slcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">your budget</span></span><span class="input_cover ng-scope"><span class="box_cover "><!-- ngRepeat: opt in option[27].Drop --><div ng-repeat="opt in option[27].Drop" class="ng-scope"><span class="slider_txt ng-binding">No. of Rooms</span><span id="slider_5_0_1_5_val" class="slider_val">0</span><input type="hidden" id="slider_5_0_1_5_val2" name="Other Details-No. of Rooms_slider__1___field5"><div class="slider ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" ng-style="{ width: el.wid }" id="slider_5_0_1_5" slider="" style="width: 220px;" aria-disabled="false"><div class="ui-slider-range ui-widget-header ui-slider-range-min" style="width: 0px;"></div><a class="ui-slider-handle ui-state-default ui-corner-all" href="#" style="left: 0%;"></a><div class="ui-slider-range ui-widget-header ui-slider-range-min" style="width: 0%;"></div></div></div><div ng-repeat="opt in option[27].Drop" class="ng-scope"><span class="slider_txt ng-binding">Total Occupants</span><span id="slider_5_1_1_10_val" class="slider_val">0</span><input type="hidden" id="slider_5_1_1_10_val2" name="Other Details-Total Occupants_slider__1___field5"><div class="slider ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" ng-style="{ width: el.wid }" id="slider_5_1_1_10" slider="" style="width: 220px;" aria-disabled="false"><div class="ui-slider-range ui-widget-header ui-slider-range-min" style="width: 0px;"></div><a class="ui-slider-handle ui-state-default ui-corner-all" href="#" style="left: 0%;"></a><div class="ui-slider-range ui-widget-header ui-slider-range-min" style="width: 0%;"></div></div></div><span class="inst sld ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }" style="font-size: 13px;"></span><span class="field5 valid_show" style="display: none;"></span></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_6" class="nform_li ng-scope">
<div compile="el.el_f"><span ng-style="{ marginBottom: el.divspa, marginTop: el.divspa, fontSize: el.divfs, color: el.divfc, fontFamily: el.family }" compile="el.divcap2" style="display: block; position: relative; margin-bottom: 0px; margin-top: 0px; font-size: 14px; color: rgb(102, 102, 102);" class="ng-scope"><div style=" text-align: center; width: 80%; margin-left: 10%" class="ng-scope"><hr></div></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_7" class="nform_li ng-scope">
<div compile="el.el_f"><span ng-style="{ marginBottom: el.divspa, marginTop: el.divspa, fontSize: el.divfs, color: el.divfc, fontFamily: el.family }" compile="el.divcap2" style="display: block; position: relative; margin-bottom: 20px; margin-top: 20px; font-size: 14px; color: rgb(102, 102, 102);" class="ng-scope"><div style=" text-align: center; width: 80%; margin-left: 10%; font-family: &quot;Times New Roman&quot;" class="ng-scope">Myself<hr></div></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_8" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 subl" ng-style="{ fontSize: con[0].lfs, color: con[0].lfc}" style="font-size: 14px;">Name<span class="show_1">*</span></span><span class="cap2 subl" ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">full name here</span></span><span class="input_cover text_cover ng-scope"><input type="text" ng-style="{width: el.wid}" name="Name_text__1_0_60_field8" style="width: 220px;"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }" style="font-size: 13px;"></span><span class="field8 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_9" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 subl" ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px;">Email<span class="show_0">*</span></span><span class="cap2 subl" ng-bind="el.ecap2" ng-style="{fontSize: con[0].slfs, color: con[0].slfc }">can't leave this empty</span></span><span class="input_cover text_cover ng-scope"><span class="input-append"><input type="email" ng-style="{ width: el.wid2 }" name="Email_email_email_0___field9" style="width: 194px;"><span class="add-on"><i class="icon-envelope"></i></span></span><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }" style="font-size: 13px;"></span><span class="field9 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_10" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 subl" ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px;">Country<span class="show_1">*</span></span><span class="cap2 subl" ng-bind="el.dcap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">select your country</span></span><span class="input_cover ng-scope"><select ng-style="{ width: el.wid }" name="Country_dropdown__1___field10" style="width: 234px;"><!-- ngRepeat: opt in option[29].Drop --><option ng-repeat="opt in option[29].Drop" class="ng-scope ng-binding" value="Option One">Option One</option><option ng-repeat="opt in option[29].Drop" class="ng-scope ng-binding" value="Option Two">Option Two</option><option ng-repeat="opt in option[29].Drop" class="ng-scope ng-binding" value="New Options">New Options</option><option ng-repeat="opt in option[29].Drop" class="ng-scope ng-binding" value="New Options">New Options</option><option ng-repeat="opt in option[29].Drop" class="ng-scope ng-binding" value="New Options">New Options</option><option ng-repeat="opt in option[29].Drop" class="ng-scope ng-binding" value="New Options">New Options</option></select><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }" style="font-size: 13px;"></span><span class="field10 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_11" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 subl" ng-style="{ fontSize: con[0].lfs, color: con[0].lfc}" style="font-size: 14px;">Mobile No<span class="show_1">*</span></span><span class="cap2 subl" ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }"></span></span><span class="input_cover text_cover ng-scope"><input type="text" ng-style="{width: el.wid}" name="Mobile No_text_integers_1_8_10_field11" style="width: 220px;"><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }" style="font-size: 13px;"></span><span class="field11 valid_show" style="display: none;"></span></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_12" class="nform_li ng-scope">
<div compile="el.el_f"><span ng-style="{ marginBottom: el.divspa, marginTop: el.divspa, fontSize: el.divfs, color: el.divfc, fontFamily: el.family }" compile="el.divcap2" style="display: block; position: relative; font-size: 14px; color: rgb(102, 102, 102);" class="ng-scope"><div style=" text-align: center; width: 80%; margin-left: 10%" class="ng-scope"><hr></div></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_13" class="nform_li ng-scope">
<div compile="el.el_f"><span ng-style="{ marginBottom: el.divspa, marginTop: el.divspa, fontSize: el.divfs, color: el.divfc, fontFamily: el.family }" compile="el.divcap2" style="display: block; position: relative; margin-bottom: 20px; margin-top: 20px; font-size: 14px; color: rgb(102, 102, 102);" class="ng-scope"><div style=" text-align: center; width: 80%; margin-left: 10%; font-family: &quot;Times New Roman&quot;" class="ng-scope">Special Requests<hr></div></span></div>
</li><li ng-repeat="el in build" style="padding-bottom: 8px; padding-top: 8px;" id="fe_14" class="nform_li ng-scope">
<div compile="el.el_f"><span class="cap_cover "><span class="cap1 subl" ng-style="{ fontSize: con[0].lfs, color: con[0].lfc }" style="font-size: 14px;"><span class="show_0">*</span></span><span class="cap2 subl" ng-bind="el.cap2" ng-style="{ fontSize: con[0].slfs, color: con[0].slfc }">further details</span></span><span class="input_cover text_cover ng-scope"><textarea rows="3" ng-style="{ width: el.wid }" name="_para__0_0_400_field14" style="width: 220px;"></textarea><span class="inst ng-binding" ng-style="{ fontSize: con[0].ifs, color: con[0].ifc }" style="font-size: 13px;"></span><span class="field14 valid_show" style="display: none;"></span></span></div>
</li>
</ul>
<div id="fe_submit" class="nform_li form_submit nform_li_before" style="position: relative; display: block"><button type="submit" class="submit_button nform_btn custom" ng-style="{background: con[0].sco, fontSize: con[0].sfs,  marginLeft: con[0].lp,  marginTop: con[0].tp,  marginBottom: con[0].bp,  marginRight: con[0].rp,  paddingTop: con[0].spad1,  paddingBottom: con[0].spad1,  paddingRight: con[0].spad2,  paddingLeft: con[0].spad2,  borderRadius: con[0].curve,  MozBorderRadius: con[0].curve,  WebkitBorderRadius: con[0].curve, fontFamily: con[0].sfamily, fontWeight: con[0].sbold, color: con[0].sbfco}" data-loading-text="Sending ..." style="background-color: rgb(233, 233, 233); font-size: 17px; margin-left: 0px; margin-top: 30px; margin-bottom: 40px; padding: 12px 40px; border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; font-family: 'Times New Roman'; font-weight: bold; color: rgb(105, 105, 105); background-position: initial initial; background-repeat: initial initial;">Submit</button><span class="nform_res" style="display: none;"></span></div>
</form>


</div>

<div style='height: 480px'></div>




</div>

</body>
</html>